In [1]:
import pandas as pd

splits = {'train': 'plain_text/train-00000-of-00001.parquet', 'valid': 'plain_text/validation-00000-of-00001.parquet'}
df_train = pd.read_parquet("hf://datasets/rajpurkar/squad/" + splits["train"])
df_valid = pd.read_parquet("hf://datasets/rajpurkar/squad/" + splits["valid"])
df = pd.concat([df_train, df_valid], ignore_index=True)

/Users/arnoochka/miniconda3/envs/subd/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
df.head(5)

,id,title,context,question,answers
0,5733be284776f41900661182,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",To whom did the Virgin Mary allegedly appear i...,"{'text': ['Saint Bernadette Soubirous'], 'answ..."
1,5733be284776f4190066117f,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What is in front of the Notre Dame Main Building?,"{'text': ['a copper statue of Christ'], 'answe..."
2,5733be284776f41900661180,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",The Basilica of the Sacred heart at Notre Dame...,"{'text': ['the Main Building'], 'answer_start'..."
3,5733be284776f41900661181,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What is the Grotto at Notre Dame?,{'text': ['a Marian place of prayer and reflec...
4,5733be284776f4190066117e,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What sits on top of the Main Building at Notre...,{'text': ['a golden statue of the Virgin Mary'...

In [3]:
unique = {'column': [], 'percentage': []}
for column in df.columns:
    try:
        unique['percentage'].append(len(df[column].unique()) / len(df))
        unique['column'].append(column)
    except TypeError:
        print(f"NOT: {column}")
    
pd.DataFrame(unique)

NOT: answers

     column  percentage
0        id    1.000000
1     title    0.004991
2   context    0.213489
3  question    0.997138

In [4]:
for col, val in df_train.loc[20].items():
    print(f"{col}:\n{val}\n")

id:
5733a70c4776f41900660f64

title:
University_of_Notre_Dame

context:
All of Notre Dame's undergraduate students are a part of one of the five undergraduate colleges at the school or are in the First Year of Studies program. The First Year of Studies program was established in 1962 to guide incoming freshmen in their first year at the school before they have declared a major. Each student is given an academic advisor from the program who helps them to choose classes that give them exposure to any major in which they are interested. The program also includes a Learning Resource Center which provides time management, collaborative learning, and subject tutoring. This program has been recognized previously, by U.S. News & World Report, as outstanding.

question:
What entity provides help with the management of time for new students at Notre Dame?

answers:
{'text': array(['Learning Resource Center'], dtype=object), 'answer_start': array([496], dtype=int32)}

In [5]:
for col, val in df_valid.loc[2].items():
    print(f"{col}:\n{val}\n")

id:
56be4db0acb8001400a502ee

title:
Super_Bowl_50

context:
Super Bowl 50 was an American football game to determine the champion of the National Football League (NFL) for the 2015 season. The American Football Conference (AFC) champion Denver Broncos defeated the National Football Conference (NFC) champion Carolina Panthers 24–10 to earn their third Super Bowl title. The game was played on February 7, 2016, at Levi's Stadium in the San Francisco Bay Area at Santa Clara, California. As this was the 50th Super Bowl, the league emphasized the "golden anniversary" with various gold-themed initiatives, as well as temporarily suspending the tradition of naming each Super Bowl game with Roman numerals (under which the game would have been known as "Super Bowl L"), so that the logo could prominently feature the Arabic numerals 50.

question:
Where did Super Bowl 50 take place?

answers:
{'text': array(['Santa Clara, California', "Levi's Stadium",
       "Levi's Stadium in the San Francisco Bay Area at Santa Clara, California."],
      dtype=object), 'answer_start': array([403, 355, 355], dtype=int32)}